apiVersion: apps/v1
kind: Deployment
metadata:
  name: openalpr-proxy-wob
  labels:
    app: openalpr-proxy-wob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openalpr-proxy-wob
  template:
    metadata:
      labels:
        app: openalpr-proxy-wob
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - perl
                - host.local
      containers:
      - name: openalpr-proxy-wob
        image: 10.1.1.1:27443/openalpr-proxy-weight:v1
        imagePullPolicy: Always
        env:
        - name: APP_NAME
          value: "openalpr"
        - name: SSH_USER
          value: "ngd"
        - name: NUM_THREADS
          value: "16"
        - name: REFRESH_SECONDS
          value: "5"
        - name: API_SERVER
          value: "https://10.1.1.1:6443"
        - name: SELF_SERVER
          value: "http://localhost:4570"
        - name: STRATEGY
          value: WEIGHT_ON_BUSY
        - name: MIN_CPU_FOR_WEIGHT
          value: "0.9"
        ports:
        - containerPort: 4570

