{{- $appname := include "openalpr.fullname" . -}}
{{- $svcname := "svc-" + $appname -}}
{{- $proxyname := $appname + "-proxy" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcname }}
spec:
  selector:
    app: {{ $proxyname }}
  ports:
    - protocol: TCP
      port: {{ .Values.proxy.port }}
      targetPort: {{ .Values.proxy.port }}
  type: LoadBalancer
