apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APPNAME-proxy-$MODE
  labels:
    app: $APPNAME-proxy-$MODE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APPNAME-proxy-$MODE
  template:
    metadata:
      labels:
        app: $APPNAME-proxy-$MODE
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - perl
                - host.local
      containers:
      - name: $APPNAME-proxy-$MODE
        image: ${REGISTRY}/demo-proxy:v1
        imagePullPolicy: Always
        env:
        - name: APP_NAME
          value: "$APPNAME"
        - name: SSH_USER
          value: "ngd"
        - name: NUM_THREADS
          value: "16"
        - name: REFRESH_SECONDS
          value: "5"
        - name: API_SERVER
          value: "https://10.1.1.1:6443"
        - name: SELF_SERVER
          value: "http://localhost:4570"
        - name: STRATEGY
          value: "$STRATEGY"
        - name: MIN_CPU_FOR_WEIGHT
          value: "0.9"
        - name: MOVING_AVERAGE_LEN
          value: "1"
        - name: ON_BUSY
          value: "$ONBUSY"
        - name: TIME_TO_WEIGHT
          value: "time_to_weight_3"
        ports:
        - containerPort: 4570

