#!/bin/bash

APPNAME=$1
MODE=$2

DEPLOY_PROXY_TEMPLATE="./templates/deploy-proxy.template.yaml"
DEPLOY_PROXY=".deploy-proxy.yaml"
DEPLOY_SVC_TEMPLATE="./templates/svc.template.yaml"
DEPLOY_SVC=".svc.yaml"


function check_sintax
{
    if [ -z "$APPNAME" -o -z "$MODE" ]; then
        echo "Sintax: $0 <APPNAME> <MODE>"
        exit 1
    fi
}

function unexpose
{
    ./undeploy_proxy
}

function expose_with_default_lb
{
    export APPNAME=$1
    cat $DEPLOY_SVC_TEMPLATE | envsubst > $DEPLOY_SVC
    sudo kubectl apply -f $DEPLOY_SVC
}

function expose_with_custom_lb
{
    export APPNAME=$1
    export MODE=$2
    export STRATEGY=$3
    export ONBUSY=$4
    cat $DEPLOY_PROXY_TEMPLATE | envsubst > $DEPLOY_PROXY
    sudo kubectl apply -f $DEPLOY_PROXY

    # Expose the proxy
    expose_with_default_lb "$APPNAME-proxy-$MODE"
}

function do_expose
{
    if [ "$MODE" == "default" ]; then
        expose_with_default_lb $APPNAME
    
    elif [ "$MODE" == "aw" ]; then
        expose_with_custom_lb $APPNAME $MODE "ADAPTIVE_WEIGHT" 0

    elif [ "$MODE" == "awob" ]; then
        expose_with_custom_lb $APPNAME $MODE "ADAPTIVE_WEIGHT" 1

    elif [ "$MODE" == "m" ]; then
        expose_with_custom_lb $APPNAME $MODE "MIN" 0

    elif [ "$MODE" == "r" ]; then
        expose_with_custom_lb $APPNAME $MODE "RANDOM" 0

    elif [ "$MODE" == "w" ]; then
        expose_with_custom_lb $APPNAME $MODE "WEIGHT" 0
    
    elif [ "$MODE" == "wob" ]; then
        expose_with_custom_lb $APPNAME $MODE "WEIGHT" 1
        
    else
        echo "Unknown mode: $MODE"
        exit 1
    fi
}

check_sintax
unexpose
do_expose
./wait_run
