#!/bin/bash

function summary
{
    sleep 1

    PODS=`sudo kubectl get pods`

    CC=`echo "$PODS" | grep ContainerCreating | wc -l`
    PE=`echo "$PODS" | grep Pending | wc -l`
    EIP=`echo "$PODS" | grep ErrImagePull | wc -l`
    IPBF=`echo "$PODS" | grep ImagePullBackOff | wc -l`
    CLBO=`echo "$PODS" | grep CrashLoopBackOff | wc -l`
    ERR=`echo "$PODS" | grep Error | wc -l`
    RUN=`echo "$PODS" | grep Running | wc -l`

    echo "Summary: ContainerCreating=$CC, Pending=$PE, ErrImagePull=$EIP, ImagePullBackOff=$IPBF, CrashLoopBackOff=$CLBO, Error=$ERR, Running=$RUN"
}

summary

while [ $CC != '0' -o $PE != '0' ]
do
    summary
done

